"""
Saudi Arabia Restaurant Menu Nutrition Data
Covers major chains operating in KSA with approximate nutrition values.
"""

RESTAURANTS: dict = {
    "al_baik": {
        "name_en": "Al Baik",
        "name_ar": "البيك",
        "category": "Saudi Fast Food",
        "emoji": "🍗",
        "color": "#e8a020",
        "items": [
            {"name_en": "Broasted Chicken 1 Piece",       "name_ar": "دجاج برستد قطعة",           "category": "Main",    "calories": 285, "protein_g": 22, "carbs_g": 14, "fat_g": 16, "sodium_mg": 620,  "fiber_g": 0},
            {"name_en": "Broasted Chicken 2 Pieces",      "name_ar": "دجاج برستد 2 قطعة",         "category": "Main",    "calories": 570, "protein_g": 44, "carbs_g": 28, "fat_g": 32, "sodium_mg": 1240, "fiber_g": 0},
            {"name_en": "Broasted Chicken 3 Pieces",      "name_ar": "دجاج برستد 3 قطع",          "category": "Main",    "calories": 855, "protein_g": 66, "carbs_g": 42, "fat_g": 48, "sodium_mg": 1860, "fiber_g": 0},
            {"name_en": "Broasted Chicken 6 Pieces",      "name_ar": "دجاج برستد 6 قطع",          "category": "Main",    "calories": 1710,"protein_g": 132,"carbs_g": 84, "fat_g": 96, "sodium_mg": 3720, "fiber_g": 0},
            {"name_en": "Fish Fillet Sandwich",           "name_ar": "ساندويش فيليه سمك",          "category": "Sandwich","calories": 430, "protein_g": 20, "carbs_g": 42, "fat_g": 20, "sodium_mg": 780,  "fiber_g": 2},
            {"name_en": "Shrimp Basket Small",            "name_ar": "سلة روبيان صغيرة",           "category": "Main",    "calories": 380, "protein_g": 24, "carbs_g": 28, "fat_g": 18, "sodium_mg": 840,  "fiber_g": 1},
            {"name_en": "Shrimp Basket Large",            "name_ar": "سلة روبيان كبيرة",           "category": "Main",    "calories": 680, "protein_g": 44, "carbs_g": 50, "fat_g": 32, "sodium_mg": 1520, "fiber_g": 2},
            {"name_en": "French Fries Small",             "name_ar": "بطاطس مقلية صغير",           "category": "Side",    "calories": 230, "protein_g": 3,  "carbs_g": 30, "fat_g": 12, "sodium_mg": 320,  "fiber_g": 2},
            {"name_en": "French Fries Medium",            "name_ar": "بطاطس مقلية وسط",            "category": "Side",    "calories": 320, "protein_g": 4,  "carbs_g": 42, "fat_g": 16, "sodium_mg": 440,  "fiber_g": 3},
            {"name_en": "French Fries Large",             "name_ar": "بطاطس مقلية كبير",           "category": "Side",    "calories": 420, "protein_g": 5,  "carbs_g": 56, "fat_g": 20, "sodium_mg": 580,  "fiber_g": 4},
            {"name_en": "Coleslaw",                       "name_ar": "كول سلو",                    "category": "Side",    "calories": 180, "protein_g": 2,  "carbs_g": 20, "fat_g": 10, "sodium_mg": 310,  "fiber_g": 2},
            {"name_en": "Garlic Sauce",                   "name_ar": "صلصة ثوم",                   "category": "Sauce",   "calories": 90,  "protein_g": 0,  "carbs_g": 2,  "fat_g": 9,  "sodium_mg": 150,  "fiber_g": 0},
            {"name_en": "Soft Drink Medium",              "name_ar": "مشروب غازي وسط",             "category": "Drink",   "calories": 150, "protein_g": 0,  "carbs_g": 38, "fat_g": 0,  "sodium_mg": 30,   "fiber_g": 0},
        ],
    },

    "kudu": {
        "name_en": "Kudu",
        "name_ar": "كودو",
        "category": "Saudi Fast Food",
        "emoji": "🍔",
        "color": "#c0392b",
        "items": [
            {"name_en": "Kudu Classic Burger",            "name_ar": "برغر كودو كلاسيك",           "category": "Burger",  "calories": 550, "protein_g": 28, "carbs_g": 44, "fat_g": 28, "sodium_mg": 920,  "fiber_g": 2},
            {"name_en": "Kudu Double Burger",             "name_ar": "برغر كودو دبل",              "category": "Burger",  "calories": 820, "protein_g": 48, "carbs_g": 46, "fat_g": 48, "sodium_mg": 1380, "fiber_g": 2},
            {"name_en": "Crispy Chicken Sandwich",        "name_ar": "ساندويش دجاج كريسبي",        "category": "Sandwich","calories": 490, "protein_g": 26, "carbs_g": 46, "fat_g": 22, "sodium_mg": 860,  "fiber_g": 2},
            {"name_en": "Grilled Chicken Sandwich",       "name_ar": "ساندويش دجاج مشوي",          "category": "Sandwich","calories": 380, "protein_g": 32, "carbs_g": 38, "fat_g": 12, "sodium_mg": 720,  "fiber_g": 2},
            {"name_en": "Fish Sandwich",                  "name_ar": "ساندويش سمك",                "category": "Sandwich","calories": 440, "protein_g": 20, "carbs_g": 44, "fat_g": 20, "sodium_mg": 780,  "fiber_g": 2},
            {"name_en": "French Fries Medium",            "name_ar": "بطاطس مقلية وسط",            "category": "Side",    "calories": 350, "protein_g": 4,  "carbs_g": 46, "fat_g": 16, "sodium_mg": 460,  "fiber_g": 3},
            {"name_en": "Onion Rings",                    "name_ar": "حلقات بصل",                  "category": "Side",    "calories": 310, "protein_g": 4,  "carbs_g": 38, "fat_g": 15, "sodium_mg": 540,  "fiber_g": 2},
            {"name_en": "Milkshake Chocolate",            "name_ar": "ميلك شيك شوكولاتة",          "category": "Drink",   "calories": 520, "protein_g": 12, "carbs_g": 78, "fat_g": 18, "sodium_mg": 280,  "fiber_g": 0},
        ],
    },

    "herfy": {
        "name_en": "Herfy",
        "name_ar": "هرفي",
        "category": "Saudi Fast Food",
        "emoji": "🍔",
        "color": "#e67e22",
        "items": [
            {"name_en": "Herfy Burger",                   "name_ar": "برغر هرفي",                  "category": "Burger",  "calories": 580, "protein_g": 30, "carbs_g": 44, "fat_g": 30, "sodium_mg": 980,  "fiber_g": 2},
            {"name_en": "Double Herfy",                   "name_ar": "برغر هرفي دبل",              "category": "Burger",  "calories": 840, "protein_g": 52, "carbs_g": 46, "fat_g": 50, "sodium_mg": 1440, "fiber_g": 2},
            {"name_en": "Herfy Mushroom Burger",          "name_ar": "برغر هرفي مشروم",            "category": "Burger",  "calories": 640, "protein_g": 32, "carbs_g": 48, "fat_g": 34, "sodium_mg": 1060, "fiber_g": 2},
            {"name_en": "Chicken Sandwich",               "name_ar": "ساندويش دجاج",               "category": "Sandwich","calories": 510, "protein_g": 27, "carbs_g": 45, "fat_g": 24, "sodium_mg": 890,  "fiber_g": 2},
            {"name_en": "Fish Sandwich",                  "name_ar": "ساندويش سمك",                "category": "Sandwich","calories": 450, "protein_g": 21, "carbs_g": 44, "fat_g": 20, "sodium_mg": 800,  "fiber_g": 2},
            {"name_en": "French Fries Medium",            "name_ar": "بطاطس مقلية وسط",            "category": "Side",    "calories": 340, "protein_g": 4,  "carbs_g": 44, "fat_g": 16, "sodium_mg": 450,  "fiber_g": 3},
            {"name_en": "Onion Rings Medium",             "name_ar": "حلقات بصل وسط",              "category": "Side",    "calories": 300, "protein_g": 3,  "carbs_g": 36, "fat_g": 15, "sodium_mg": 510,  "fiber_g": 2},
            {"name_en": "Kids Meal Burger",               "name_ar": "وجبة أطفال برغر",            "category": "Kids",    "calories": 420, "protein_g": 18, "carbs_g": 42, "fat_g": 20, "sodium_mg": 680,  "fiber_g": 2},
        ],
    },

    "shawarmer": {
        "name_en": "Shawarmer",
        "name_ar": "شاورمر",
        "category": "Saudi Fast Food",
        "emoji": "🥙",
        "color": "#8e44ad",
        "items": [
            {"name_en": "Chicken Shawarma Sandwich",      "name_ar": "ساندويش شاورما دجاج",        "category": "Sandwich","calories": 380, "protein_g": 28, "carbs_g": 38, "fat_g": 12, "sodium_mg": 820,  "fiber_g": 3},
            {"name_en": "Meat Shawarma Sandwich",         "name_ar": "ساندويش شاورما لحم",         "category": "Sandwich","calories": 420, "protein_g": 26, "carbs_g": 36, "fat_g": 18, "sodium_mg": 880,  "fiber_g": 2},
            {"name_en": "Mixed Shawarma Sandwich",        "name_ar": "ساندويش شاورما مشكل",        "category": "Sandwich","calories": 400, "protein_g": 27, "carbs_g": 37, "fat_g": 15, "sodium_mg": 850,  "fiber_g": 3},
            {"name_en": "Chicken Shawarma Plate",         "name_ar": "طبق شاورما دجاج",            "category": "Main",    "calories": 650, "protein_g": 48, "carbs_g": 58, "fat_g": 22, "sodium_mg": 1380, "fiber_g": 4},
            {"name_en": "Meat Shawarma Plate",            "name_ar": "طبق شاورما لحم",             "category": "Main",    "calories": 720, "protein_g": 46, "carbs_g": 60, "fat_g": 28, "sodium_mg": 1440, "fiber_g": 4},
            {"name_en": "Mixed Plate",                    "name_ar": "طبق مشكل",                   "category": "Main",    "calories": 680, "protein_g": 47, "carbs_g": 59, "fat_g": 25, "sodium_mg": 1410, "fiber_g": 4},
            {"name_en": "French Fries",                   "name_ar": "بطاطس مقلية",                "category": "Side",    "calories": 330, "protein_g": 4,  "carbs_g": 43, "fat_g": 16, "sodium_mg": 420,  "fiber_g": 3},
            {"name_en": "Garlic Sauce",                   "name_ar": "صلصة ثوم",                   "category": "Sauce",   "calories": 95,  "protein_g": 0,  "carbs_g": 2,  "fat_g": 10, "sodium_mg": 160,  "fiber_g": 0},
        ],
    },

    "mcdonalds": {
        "name_en": "McDonald's",
        "name_ar": "ماكدونالدز",
        "category": "International Fast Food",
        "emoji": "🍟",
        "color": "#f0a500",
        "items": [
            {"name_en": "Big Mac",                        "name_ar": "بيغ ماك",                    "category": "Burger",  "calories": 550, "protein_g": 25, "carbs_g": 45, "fat_g": 30, "sodium_mg": 1010, "fiber_g": 3},
            {"name_en": "McArabia Chicken",               "name_ar": "مك عربيا دجاج",              "category": "Sandwich","calories": 450, "protein_g": 28, "carbs_g": 42, "fat_g": 18, "sodium_mg": 870,  "fiber_g": 3},
            {"name_en": "McArabia Kofta",                 "name_ar": "مك عربيا كفتة",              "category": "Sandwich","calories": 480, "protein_g": 26, "carbs_g": 44, "fat_g": 20, "sodium_mg": 900,  "fiber_g": 3},
            {"name_en": "Quarter Pounder with Cheese",    "name_ar": "كوارتر باوندر بالجبن",       "category": "Burger",  "calories": 510, "protein_g": 29, "carbs_g": 42, "fat_g": 26, "sodium_mg": 1110, "fiber_g": 2},
            {"name_en": "Double Quarter Pounder",         "name_ar": "دبل كوارتر باوندر",          "category": "Burger",  "calories": 740, "protein_g": 48, "carbs_g": 43, "fat_g": 42, "sodium_mg": 1280, "fiber_g": 2},
            {"name_en": "McChicken",                      "name_ar": "ماك تشيكن",                  "category": "Sandwich","calories": 430, "protein_g": 22, "carbs_g": 41, "fat_g": 20, "sodium_mg": 760,  "fiber_g": 2},
            {"name_en": "Filet-O-Fish",                   "name_ar": "فيليه أو فيش",               "category": "Sandwich","calories": 390, "protein_g": 16, "carbs_g": 38, "fat_g": 19, "sodium_mg": 710,  "fiber_g": 1},
            {"name_en": "French Fries Medium",            "name_ar": "بطاطس مقلية وسط",            "category": "Side",    "calories": 340, "protein_g": 4,  "carbs_g": 44, "fat_g": 16, "sodium_mg": 400,  "fiber_g": 4},
            {"name_en": "French Fries Large",             "name_ar": "بطاطس مقلية كبير",           "category": "Side",    "calories": 490, "protein_g": 6,  "carbs_g": 66, "fat_g": 23, "sodium_mg": 580,  "fiber_g": 6},
            {"name_en": "Chicken McNuggets 6 pieces",     "name_ar": "تشيكن ماكنجتس 6 قطع",       "category": "Side",    "calories": 280, "protein_g": 18, "carbs_g": 17, "fat_g": 16, "sodium_mg": 510,  "fiber_g": 1},
            {"name_en": "Chicken McNuggets 9 pieces",     "name_ar": "تشيكن ماكنجتس 9 قطع",       "category": "Side",    "calories": 420, "protein_g": 27, "carbs_g": 26, "fat_g": 24, "sodium_mg": 760,  "fiber_g": 2},
            {"name_en": "McFlurry Oreo",                  "name_ar": "مك فلوري أوريو",             "category": "Dessert", "calories": 350, "protein_g": 9,  "carbs_g": 52, "fat_g": 12, "sodium_mg": 190,  "fiber_g": 1},
            {"name_en": "Apple Pie",                      "name_ar": "باي التفاح",                 "category": "Dessert", "calories": 260, "protein_g": 3,  "carbs_g": 34, "fat_g": 13, "sodium_mg": 200,  "fiber_g": 1},
        ],
    },

    "kfc": {
        "name_en": "KFC",
        "name_ar": "كنتاكي",
        "category": "International Fast Food",
        "emoji": "🍗",
        "color": "#e31837",
        "items": [
            {"name_en": "Original Recipe Chicken Breast", "name_ar": "دجاج أصلي (صدر)",            "category": "Main",    "calories": 380, "protein_g": 38, "carbs_g": 11, "fat_g": 21, "sodium_mg": 970,  "fiber_g": 0},
            {"name_en": "Original Recipe Chicken Thigh",  "name_ar": "دجاج أصلي (فخذ)",            "category": "Main",    "calories": 290, "protein_g": 24, "carbs_g": 9,  "fat_g": 18, "sodium_mg": 750,  "fiber_g": 0},
            {"name_en": "Zinger Burger",                  "name_ar": "زينجر برغر",                 "category": "Burger",  "calories": 590, "protein_g": 31, "carbs_g": 52, "fat_g": 28, "sodium_mg": 1050, "fiber_g": 2},
            {"name_en": "Tower Burger",                   "name_ar": "تاور برغر",                  "category": "Burger",  "calories": 640, "protein_g": 33, "carbs_g": 54, "fat_g": 32, "sodium_mg": 1120, "fiber_g": 2},
            {"name_en": "Hot Wings 5 Pieces",             "name_ar": "هوت وينجز 5 قطع",            "category": "Main",    "calories": 430, "protein_g": 28, "carbs_g": 24, "fat_g": 24, "sodium_mg": 840,  "fiber_g": 1},
            {"name_en": "Popcorn Chicken Regular",        "name_ar": "بوبكورن تشيكن عادي",         "category": "Main",    "calories": 350, "protein_g": 22, "carbs_g": 28, "fat_g": 16, "sodium_mg": 720,  "fiber_g": 1},
            {"name_en": "Coleslaw",                       "name_ar": "كول سلو",                    "category": "Side",    "calories": 140, "protein_g": 2,  "carbs_g": 18, "fat_g": 7,  "sodium_mg": 260,  "fiber_g": 2},
            {"name_en": "Corn on the Cob",                "name_ar": "ذرة على العرنوس",            "category": "Side",    "calories": 70,  "protein_g": 2,  "carbs_g": 14, "fat_g": 1,  "sodium_mg": 5,    "fiber_g": 2},
            {"name_en": "Mashed Potatoes",                "name_ar": "بطاطا مهروسة",               "category": "Side",    "calories": 130, "protein_g": 3,  "carbs_g": 24, "fat_g": 4,  "sodium_mg": 520,  "fiber_g": 2},
            {"name_en": "Pepsi Medium",                   "name_ar": "بيبسي وسط",                  "category": "Drink",   "calories": 150, "protein_g": 0,  "carbs_g": 40, "fat_g": 0,  "sodium_mg": 25,   "fiber_g": 0},
        ],
    },

    "burger_king": {
        "name_en": "Burger King",
        "name_ar": "برغر كنج",
        "category": "International Fast Food",
        "emoji": "👑",
        "color": "#f5a623",
        "items": [
            {"name_en": "Whopper",                        "name_ar": "واپر",                        "category": "Burger",  "calories": 680, "protein_g": 28, "carbs_g": 49, "fat_g": 40, "sodium_mg": 980,  "fiber_g": 2},
            {"name_en": "Double Whopper",                 "name_ar": "دبل واپر",                    "category": "Burger",  "calories": 900, "protein_g": 48, "carbs_g": 50, "fat_g": 56, "sodium_mg": 1200, "fiber_g": 2},
            {"name_en": "Whopper with Cheese",            "name_ar": "واپر بالجبن",                "category": "Burger",  "calories": 740, "protein_g": 32, "carbs_g": 50, "fat_g": 46, "sodium_mg": 1200, "fiber_g": 2},
            {"name_en": "Chicken Royale",                 "name_ar": "تشيكن رويال",                "category": "Burger",  "calories": 520, "protein_g": 26, "carbs_g": 50, "fat_g": 24, "sodium_mg": 1050, "fiber_g": 2},
            {"name_en": "Big King",                       "name_ar": "بيغ كنج",                    "category": "Burger",  "calories": 620, "protein_g": 32, "carbs_g": 44, "fat_g": 34, "sodium_mg": 1080, "fiber_g": 2},
            {"name_en": "French Fries Medium",            "name_ar": "بطاطس مقلية وسط",            "category": "Side",    "calories": 340, "protein_g": 4,  "carbs_g": 44, "fat_g": 16, "sodium_mg": 570,  "fiber_g": 3},
            {"name_en": "Onion Rings Medium",             "name_ar": "حلقات بصل وسط",              "category": "Side",    "calories": 320, "protein_g": 4,  "carbs_g": 38, "fat_g": 16, "sodium_mg": 540,  "fiber_g": 3},
            {"name_en": "Chicken Nuggets 8 pieces",       "name_ar": "تشيكن ناجتس 8 قطع",         "category": "Side",    "calories": 330, "protein_g": 18, "carbs_g": 20, "fat_g": 19, "sodium_mg": 660,  "fiber_g": 1},
            {"name_en": "Sundae Chocolate",               "name_ar": "صندي شوكولاتة",              "category": "Dessert", "calories": 280, "protein_g": 6,  "carbs_g": 42, "fat_g": 10, "sodium_mg": 140,  "fiber_g": 0},
        ],
    },

    "pizza_hut": {
        "name_en": "Pizza Hut",
        "name_ar": "بيتزا هت",
        "category": "Pizza",
        "emoji": "🍕",
        "color": "#e31837",
        "items": [
            {"name_en": "Cheese Pizza 1 Slice (Regular)",     "name_ar": "بيتزا جبن 1 شريحة (عادي)",    "category": "Pizza", "calories": 250, "protein_g": 11, "carbs_g": 28, "fat_g": 10, "sodium_mg": 480,  "fiber_g": 1},
            {"name_en": "Pepperoni Pizza 1 Slice (Regular)",  "name_ar": "بيتزا ببيروني 1 شريحة",       "category": "Pizza", "calories": 290, "protein_g": 13, "carbs_g": 28, "fat_g": 14, "sodium_mg": 640,  "fiber_g": 1},
            {"name_en": "Meat Lovers 1 Slice",                "name_ar": "بيتزا لحوم 1 شريحة",          "category": "Pizza", "calories": 340, "protein_g": 16, "carbs_g": 29, "fat_g": 18, "sodium_mg": 780,  "fiber_g": 1},
            {"name_en": "BBQ Chicken Pizza 1 Slice",          "name_ar": "بيتزا دجاج بي بي كيو شريحة", "category": "Pizza", "calories": 280, "protein_g": 15, "carbs_g": 31, "fat_g": 11, "sodium_mg": 580,  "fiber_g": 2},
            {"name_en": "Veggie Pizza 1 Slice",               "name_ar": "بيتزا خضروات شريحة",          "category": "Pizza", "calories": 220, "protein_g": 10, "carbs_g": 27, "fat_g": 9,  "sodium_mg": 420,  "fiber_g": 2},
            {"name_en": "Cheesy Bites Pizza 1 Slice",         "name_ar": "بيتزا تشيزي بايتس شريحة",    "category": "Pizza", "calories": 320, "protein_g": 14, "carbs_g": 32, "fat_g": 16, "sodium_mg": 620,  "fiber_g": 1},
            {"name_en": "Chicken Wings 6 pieces",             "name_ar": "أجنحة دجاج 6 قطع",            "category": "Side",  "calories": 460, "protein_g": 32, "carbs_g": 10, "fat_g": 32, "sodium_mg": 880,  "fiber_g": 0},
            {"name_en": "Garlic Bread",                       "name_ar": "خبز ثوم",                      "category": "Side",  "calories": 210, "protein_g": 5,  "carbs_g": 26, "fat_g": 10, "sodium_mg": 380,  "fiber_g": 1},
            {"name_en": "Pasta Bolognese",                    "name_ar": "باستا بولونيز",                "category": "Pasta", "calories": 480, "protein_g": 22, "carbs_g": 58, "fat_g": 18, "sodium_mg": 840,  "fiber_g": 3},
        ],
    },

    "dominos": {
        "name_en": "Domino's",
        "name_ar": "دومينوز",
        "category": "Pizza",
        "emoji": "🍕",
        "color": "#006491",
        "items": [
            {"name_en": "Cheese Pizza 1 Slice (Medium)",      "name_ar": "بيتزا جبن شريحة (وسط)",       "category": "Pizza", "calories": 200, "protein_g": 9,  "carbs_g": 26, "fat_g": 7,  "sodium_mg": 420,  "fiber_g": 1},
            {"name_en": "Pepperoni Pizza 1 Slice",            "name_ar": "بيتزا ببيروني شريحة",         "category": "Pizza", "calories": 240, "protein_g": 11, "carbs_g": 26, "fat_g": 11, "sodium_mg": 560,  "fiber_g": 1},
            {"name_en": "MeatZZa 1 Slice",                    "name_ar": "ميتزا شريحة",                  "category": "Pizza", "calories": 290, "protein_g": 14, "carbs_g": 27, "fat_g": 15, "sodium_mg": 680,  "fiber_g": 1},
            {"name_en": "ExtravaganZZa 1 Slice",              "name_ar": "إكسترافاغانزا شريحة",         "category": "Pizza", "calories": 310, "protein_g": 15, "carbs_g": 28, "fat_g": 16, "sodium_mg": 720,  "fiber_g": 2},
            {"name_en": "Chicken BBQ Pizza 1 Slice",          "name_ar": "بيتزا دجاج بي بي كيو شريحة", "category": "Pizza", "calories": 260, "protein_g": 14, "carbs_g": 30, "fat_g": 10, "sodium_mg": 520,  "fiber_g": 2},
            {"name_en": "Breadsticks 6 pieces",               "name_ar": "عصي الخبز 6 قطع",             "category": "Side",  "calories": 350, "protein_g": 10, "carbs_g": 52, "fat_g": 11, "sodium_mg": 640,  "fiber_g": 2},
            {"name_en": "Chicken Kickers 6 pieces",           "name_ar": "كيكرز دجاج 6 قطع",            "category": "Side",  "calories": 280, "protein_g": 20, "carbs_g": 18, "fat_g": 14, "sodium_mg": 580,  "fiber_g": 1},
            {"name_en": "Lava Cake",                          "name_ar": "لافا كيك",                     "category": "Dessert","calories": 350, "protein_g": 5,  "carbs_g": 44, "fat_g": 18, "sodium_mg": 180,  "fiber_g": 2},
        ],
    },

    "subway": {
        "name_en": "Subway",
        "name_ar": "سابواي",
        "category": "International Fast Food",
        "emoji": "🥪",
        "color": "#009b48",
        "items": [
            {"name_en": "6-inch Turkey Breast",           "name_ar": "ساندويش تركي 6 إنش",        "category": "Sandwich","calories": 280, "protein_g": 18, "carbs_g": 40, "fat_g": 4,  "sodium_mg": 680,  "fiber_g": 3},
            {"name_en": "6-inch Chicken Teriyaki",        "name_ar": "ساندويش دجاج تيرياكي 6 إنش","category": "Sandwich","calories": 380, "protein_g": 26, "carbs_g": 50, "fat_g": 7,  "sodium_mg": 760,  "fiber_g": 3},
            {"name_en": "6-inch Italian BMT",             "name_ar": "ساندويش إيطالي BMT 6 إنش", "category": "Sandwich","calories": 450, "protein_g": 22, "carbs_g": 42, "fat_g": 20, "sodium_mg": 1280, "fiber_g": 3},
            {"name_en": "6-inch Veggie Delite",           "name_ar": "ساندويش خضروات 6 إنش",      "category": "Sandwich","calories": 230, "protein_g": 9,  "carbs_g": 44, "fat_g": 2,  "sodium_mg": 310,  "fiber_g": 4},
            {"name_en": "6-inch Steak & Cheese",          "name_ar": "ساندويش ستيك وجبن 6 إنش",  "category": "Sandwich","calories": 380, "protein_g": 26, "carbs_g": 42, "fat_g": 10, "sodium_mg": 960,  "fiber_g": 3},
            {"name_en": "12-inch Turkey Breast",          "name_ar": "ساندويش تركي 12 إنش",       "category": "Sandwich","calories": 560, "protein_g": 36, "carbs_g": 80, "fat_g": 8,  "sodium_mg": 1360, "fiber_g": 6},
            {"name_en": "12-inch Italian BMT",            "name_ar": "ساندويش إيطالي BMT 12 إنش","category": "Sandwich","calories": 900, "protein_g": 44, "carbs_g": 84, "fat_g": 40, "sodium_mg": 2560, "fiber_g": 6},
            {"name_en": "Chocolate Chip Cookie",          "name_ar": "كوكيز شوكولاتة",            "category": "Dessert", "calories": 210, "protein_g": 3,  "carbs_g": 30, "fat_g": 10, "sodium_mg": 160,  "fiber_g": 1},
        ],
    },

    "popeyes": {
        "name_en": "Popeyes",
        "name_ar": "بوباي",
        "category": "International Fast Food",
        "emoji": "🍗",
        "color": "#f26522",
        "items": [
            {"name_en": "Classic Chicken Sandwich",       "name_ar": "ساندويش دجاج كلاسيك",       "category": "Sandwich","calories": 700, "protein_g": 28, "carbs_g": 69, "fat_g": 42, "sodium_mg": 1443, "fiber_g": 3},
            {"name_en": "Spicy Chicken Sandwich",         "name_ar": "ساندويش دجاج حار",          "category": "Sandwich","calories": 710, "protein_g": 28, "carbs_g": 70, "fat_g": 43, "sodium_mg": 1580, "fiber_g": 3},
            {"name_en": "Classic Chicken Breast",         "name_ar": "صدر دجاج كلاسيك",           "category": "Main",    "calories": 430, "protein_g": 34, "carbs_g": 17, "fat_g": 26, "sodium_mg": 1330, "fiber_g": 1},
            {"name_en": "Spicy Chicken Breast",           "name_ar": "صدر دجاج حار",               "category": "Main",    "calories": 440, "protein_g": 34, "carbs_g": 17, "fat_g": 27, "sodium_mg": 1540, "fiber_g": 1},
            {"name_en": "Chicken Tenders 3 pieces",       "name_ar": "تندرز دجاج 3 قطع",          "category": "Main",    "calories": 370, "protein_g": 24, "carbs_g": 28, "fat_g": 18, "sodium_mg": 960,  "fiber_g": 1},
            {"name_en": "Red Beans & Rice",               "name_ar": "فاصوليا حمراء مع أرز",      "category": "Side",    "calories": 230, "protein_g": 8,  "carbs_g": 42, "fat_g": 4,  "sodium_mg": 680,  "fiber_g": 6},
            {"name_en": "Coleslaw",                       "name_ar": "كول سلو",                    "category": "Side",    "calories": 210, "protein_g": 2,  "carbs_g": 26, "fat_g": 11, "sodium_mg": 340,  "fiber_g": 2},
            {"name_en": "Mashed Potatoes with Gravy",     "name_ar": "بطاطا مهروسة مع صلصة",      "category": "Side",    "calories": 210, "protein_g": 4,  "carbs_g": 28, "fat_g": 10, "sodium_mg": 620,  "fiber_g": 2},
        ],
    },

    "hardees": {
        "name_en": "Hardee's",
        "name_ar": "هارديز",
        "category": "International Fast Food",
        "emoji": "🍔",
        "color": "#e31837",
        "items": [
            {"name_en": "Original Thickburger",           "name_ar": "ثيكبرغر أصلي",              "category": "Burger",  "calories": 790, "protein_g": 41, "carbs_g": 58, "fat_g": 46, "sodium_mg": 1330, "fiber_g": 2},
            {"name_en": "Double Thickburger",             "name_ar": "دبل ثيكبرغر",               "category": "Burger",  "calories": 1020,"protein_g": 62, "carbs_g": 59, "fat_g": 62, "sodium_mg": 1680, "fiber_g": 2},
            {"name_en": "Mushroom & Swiss Thickburger",   "name_ar": "ثيكبرغر مشروم وجبن سويسري","category": "Burger",  "calories": 900, "protein_g": 44, "carbs_g": 60, "fat_g": 54, "sodium_mg": 1440, "fiber_g": 2},
            {"name_en": "Chicken Fillet Sandwich",        "name_ar": "ساندويش فيليه دجاج",         "category": "Sandwich","calories": 530, "protein_g": 27, "carbs_g": 52, "fat_g": 24, "sodium_mg": 1120, "fiber_g": 2},
            {"name_en": "Spicy Chicken Sandwich",         "name_ar": "ساندويش دجاج حار",          "category": "Sandwich","calories": 550, "protein_g": 28, "carbs_g": 53, "fat_g": 25, "sodium_mg": 1250, "fiber_g": 2},
            {"name_en": "Natural Cut Fries Medium",       "name_ar": "بطاطس طبيعية وسط",          "category": "Side",    "calories": 360, "protein_g": 4,  "carbs_g": 46, "fat_g": 18, "sodium_mg": 380,  "fiber_g": 4},
            {"name_en": "Curly Fries Medium",             "name_ar": "بطاطس حلزونية وسط",         "category": "Side",    "calories": 400, "protein_g": 4,  "carbs_g": 50, "fat_g": 20, "sodium_mg": 820,  "fiber_g": 4},
        ],
    },

    "nandos": {
        "name_en": "Nando's",
        "name_ar": "ناندوز",
        "category": "Casual Dining",
        "emoji": "🔥",
        "color": "#c1272d",
        "items": [
            {"name_en": "1/4 Chicken Lemon & Herb",       "name_ar": "ربع دجاجة ليمون وأعشاب",    "category": "Main",    "calories": 410, "protein_g": 42, "carbs_g": 3,  "fat_g": 26, "sodium_mg": 480,  "fiber_g": 0},
            {"name_en": "1/4 Chicken Hot",                "name_ar": "ربع دجاجة حارة",             "category": "Main",    "calories": 415, "protein_g": 42, "carbs_g": 4,  "fat_g": 26, "sodium_mg": 510,  "fiber_g": 0},
            {"name_en": "1/2 Chicken Peri Peri",          "name_ar": "نصف دجاجة بيري بيري",       "category": "Main",    "calories": 820, "protein_g": 84, "carbs_g": 6,  "fat_g": 52, "sodium_mg": 960,  "fiber_g": 0},
            {"name_en": "Full Chicken",                   "name_ar": "دجاجة كاملة",               "category": "Main",    "calories": 1640,"protein_g": 168,"carbs_g": 12, "fat_g": 104,"sodium_mg": 1920, "fiber_g": 0},
            {"name_en": "Chicken Wrap",                   "name_ar": "راب دجاج",                  "category": "Sandwich","calories": 480, "protein_g": 34, "carbs_g": 44, "fat_g": 18, "sodium_mg": 780,  "fiber_g": 3},
            {"name_en": "Peri Peri Rice",                 "name_ar": "أرز بيري بيري",              "category": "Side",    "calories": 330, "protein_g": 7,  "carbs_g": 62, "fat_g": 6,  "sodium_mg": 440,  "fiber_g": 2},
            {"name_en": "Spicy Rice",                     "name_ar": "أرز حار",                   "category": "Side",    "calories": 290, "protein_g": 6,  "carbs_g": 56, "fat_g": 4,  "sodium_mg": 380,  "fiber_g": 2},
            {"name_en": "Coleslaw",                       "name_ar": "كول سلو",                    "category": "Side",    "calories": 220, "protein_g": 2,  "carbs_g": 28, "fat_g": 11, "sodium_mg": 280,  "fiber_g": 3},
            {"name_en": "Peri Peri Chips",                "name_ar": "بطاطس بيري بيري",            "category": "Side",    "calories": 370, "protein_g": 5,  "carbs_g": 46, "fat_g": 18, "sodium_mg": 420,  "fiber_g": 4},
            {"name_en": "Chicken Livers",                 "name_ar": "كبدة دجاج",                 "category": "Starter", "calories": 310, "protein_g": 28, "carbs_g": 8,  "fat_g": 19, "sodium_mg": 560,  "fiber_g": 1},
        ],
    },

    "five_guys": {
        "name_en": "Five Guys",
        "name_ar": "فايف جايز",
        "category": "Casual Dining",
        "emoji": "🍔",
        "color": "#ce1126",
        "items": [
            {"name_en": "Hamburger",                      "name_ar": "هامبرغر",                    "category": "Burger",  "calories": 700, "protein_g": 36, "carbs_g": 40, "fat_g": 43, "sodium_mg": 430,  "fiber_g": 2},
            {"name_en": "Cheeseburger",                   "name_ar": "تشيزبرغر",                   "category": "Burger",  "calories": 840, "protein_g": 44, "carbs_g": 41, "fat_g": 55, "sodium_mg": 780,  "fiber_g": 2},
            {"name_en": "Bacon Cheeseburger",             "name_ar": "بيكون تشيزبرغر",             "category": "Burger",  "calories": 920, "protein_g": 50, "carbs_g": 41, "fat_g": 62, "sodium_mg": 1060, "fiber_g": 2},
            {"name_en": "Veggie Sandwich",                "name_ar": "ساندويش خضروات",             "category": "Sandwich","calories": 490, "protein_g": 15, "carbs_g": 60, "fat_g": 23, "sodium_mg": 410,  "fiber_g": 5},
            {"name_en": "Hot Dog",                        "name_ar": "هوت دوج",                    "category": "Main",    "calories": 580, "protein_g": 20, "carbs_g": 40, "fat_g": 38, "sodium_mg": 1050, "fiber_g": 2},
            {"name_en": "Little Fries",                   "name_ar": "بطاطس صغير",                 "category": "Side",    "calories": 530, "protein_g": 8,  "carbs_g": 71, "fat_g": 25, "sodium_mg": 320,  "fiber_g": 6},
            {"name_en": "Regular Fries",                  "name_ar": "بطاطس عادي",                 "category": "Side",    "calories": 950, "protein_g": 14, "carbs_g": 127,"fat_g": 45, "sodium_mg": 570,  "fiber_g": 11},
            {"name_en": "Cajun Fries Regular",            "name_ar": "بطاطس كاجون عادي",           "category": "Side",    "calories": 960, "protein_g": 14, "carbs_g": 128,"fat_g": 45, "sodium_mg": 1480, "fiber_g": 11},
        ],
    },

    "starbucks": {
        "name_en": "Starbucks",
        "name_ar": "ستاربكس",
        "category": "Coffee & Café",
        "emoji": "☕",
        "color": "#00704a",
        "items": [
            {"name_en": "Caramel Frappuccino Grande",     "name_ar": "كراميل فرابوتشينو غراندي",   "category": "Drink",   "calories": 420, "protein_g": 6,  "carbs_g": 65, "fat_g": 16, "sodium_mg": 230,  "fiber_g": 0},
            {"name_en": "Java Chip Frappuccino Grande",   "name_ar": "جافا شيب فرابوتشينو غراندي","category": "Drink",   "calories": 490, "protein_g": 7,  "carbs_g": 72, "fat_g": 21, "sodium_mg": 270,  "fiber_g": 2},
            {"name_en": "Vanilla Latte Grande",           "name_ar": "فانيلا لاتيه غراندي",        "category": "Drink",   "calories": 250, "protein_g": 12, "carbs_g": 37, "fat_g": 6,  "sodium_mg": 170,  "fiber_g": 0},
            {"name_en": "Cappuccino Grande",              "name_ar": "كابتشينو غراندي",            "category": "Drink",   "calories": 140, "protein_g": 8,  "carbs_g": 14, "fat_g": 5,  "sodium_mg": 100,  "fiber_g": 0},
            {"name_en": "Iced Green Tea Latte Grande",    "name_ar": "شاي أخضر بارد لاتيه غراندي","category": "Drink",   "calories": 320, "protein_g": 9,  "carbs_g": 56, "fat_g": 7,  "sodium_mg": 130,  "fiber_g": 0},
            {"name_en": "Flat White Grande",              "name_ar": "فلات وايت غراندي",           "category": "Drink",   "calories": 220, "protein_g": 12, "carbs_g": 22, "fat_g": 9,  "sodium_mg": 130,  "fiber_g": 0},
            {"name_en": "Butter Croissant",               "name_ar": "كرواسون بالزبدة",            "category": "Food",    "calories": 310, "protein_g": 6,  "carbs_g": 32, "fat_g": 18, "sodium_mg": 310,  "fiber_g": 1},
            {"name_en": "Chocolate Muffin",               "name_ar": "مافن شوكولاتة",              "category": "Food",    "calories": 450, "protein_g": 7,  "carbs_g": 62, "fat_g": 20, "sodium_mg": 340,  "fiber_g": 3},
            {"name_en": "Chicken Caesar Sandwich",        "name_ar": "ساندويش دجاج سيزر",          "category": "Food",    "calories": 420, "protein_g": 26, "carbs_g": 40, "fat_g": 16, "sodium_mg": 820,  "fiber_g": 2},
        ],
    },

    "dunkin": {
        "name_en": "Dunkin'",
        "name_ar": "دانكن",
        "category": "Coffee & Café",
        "emoji": "🍩",
        "color": "#ff671f",
        "items": [
            {"name_en": "Original Glazed Donut",          "name_ar": "دونات مزجج أصلي",           "category": "Dessert", "calories": 260, "protein_g": 4,  "carbs_g": 31, "fat_g": 14, "sodium_mg": 260,  "fiber_g": 1},
            {"name_en": "Chocolate Glazed Donut",         "name_ar": "دونات مزجج شوكولاتة",       "category": "Dessert", "calories": 280, "protein_g": 4,  "carbs_g": 33, "fat_g": 15, "sodium_mg": 280,  "fiber_g": 1},
            {"name_en": "Boston Kreme Donut",             "name_ar": "دونات بوسطن كريم",          "category": "Dessert", "calories": 300, "protein_g": 4,  "carbs_g": 38, "fat_g": 14, "sodium_mg": 280,  "fiber_g": 1},
            {"name_en": "Croissant",                      "name_ar": "كرواسون",                   "category": "Food",    "calories": 360, "protein_g": 8,  "carbs_g": 36, "fat_g": 20, "sodium_mg": 430,  "fiber_g": 1},
            {"name_en": "Iced Coffee Medium",             "name_ar": "قهوة مثلجة وسط",            "category": "Drink",   "calories": 260, "protein_g": 8,  "carbs_g": 44, "fat_g": 6,  "sodium_mg": 230,  "fiber_g": 0},
            {"name_en": "Original Blend Coffee Medium",   "name_ar": "قهوة أصلية وسط",            "category": "Drink",   "calories": 5,   "protein_g": 0,  "carbs_g": 1,  "fat_g": 0,  "sodium_mg": 10,   "fiber_g": 0},
            {"name_en": "Hot Chocolate Medium",           "name_ar": "شوكولاتة ساخنة وسط",        "category": "Drink",   "calories": 330, "protein_g": 10, "carbs_g": 52, "fat_g": 9,  "sodium_mg": 280,  "fiber_g": 2},
            {"name_en": "Egg & Cheese Sandwich",          "name_ar": "ساندويش بيض وجبن",          "category": "Food",    "calories": 390, "protein_g": 17, "carbs_g": 42, "fat_g": 17, "sodium_mg": 850,  "fiber_g": 2},
        ],
    },

    "tim_hortons": {
        "name_en": "Tim Hortons",
        "name_ar": "تيم هورتنز",
        "category": "Coffee & Café",
        "emoji": "☕",
        "color": "#d11c2c",
        "items": [
            {"name_en": "Original Blend Coffee Medium",   "name_ar": "قهوة بليند أصلية وسط",      "category": "Drink",   "calories": 5,   "protein_g": 0,  "carbs_g": 1,  "fat_g": 0,  "sodium_mg": 5,    "fiber_g": 0},
            {"name_en": "French Vanilla Medium",          "name_ar": "فرنش فانيلا وسط",           "category": "Drink",   "calories": 270, "protein_g": 8,  "carbs_g": 42, "fat_g": 8,  "sodium_mg": 135,  "fiber_g": 0},
            {"name_en": "Iced Capp Medium",               "name_ar": "آيسد كاب وسط",              "category": "Drink",   "calories": 290, "protein_g": 5,  "carbs_g": 44, "fat_g": 10, "sodium_mg": 115,  "fiber_g": 0},
            {"name_en": "Hot Chocolate Medium",           "name_ar": "شوكولاتة ساخنة وسط",        "category": "Drink",   "calories": 240, "protein_g": 9,  "carbs_g": 42, "fat_g": 5,  "sodium_mg": 165,  "fiber_g": 2},
            {"name_en": "Chocolate Chip Cookie",          "name_ar": "كوكيز شوكولاتة",            "category": "Dessert", "calories": 270, "protein_g": 3,  "carbs_g": 37, "fat_g": 13, "sodium_mg": 170,  "fiber_g": 1},
            {"name_en": "Timbiebs Timbits (each)",        "name_ar": "تيمبيتس (الحبة)",           "category": "Dessert", "calories": 70,  "protein_g": 1,  "carbs_g": 10, "fat_g": 3,  "sodium_mg": 65,   "fiber_g": 0},
            {"name_en": "BLT Sandwich",                   "name_ar": "ساندويش BLT",               "category": "Food",    "calories": 450, "protein_g": 18, "carbs_g": 44, "fat_g": 22, "sodium_mg": 1080, "fiber_g": 3},
            {"name_en": "Grilled Chicken Sandwich",       "name_ar": "ساندويش دجاج مشوي",         "category": "Food",    "calories": 420, "protein_g": 28, "carbs_g": 42, "fat_g": 14, "sodium_mg": 880,  "fiber_g": 3},
        ],
    },

    "laziz": {
        "name_en": "Laziz",
        "name_ar": "لذيذ",
        "category": "Saudi Fast Food",
        "emoji": "🍗",
        "color": "#e8a020",
        "items": [
            {"name_en": "Laziz Chicken Bucket 4 pieces",  "name_ar": "دلو دجاج لذيذ 4 قطع",       "category": "Main",    "calories": 1020,"protein_g": 80, "carbs_g": 60, "fat_g": 52, "sodium_mg": 2200, "fiber_g": 2},
            {"name_en": "Laziz Chicken 2 pieces",         "name_ar": "دجاج لذيذ 2 قطعة",          "category": "Main",    "calories": 510, "protein_g": 40, "carbs_g": 30, "fat_g": 26, "sodium_mg": 1100, "fiber_g": 1},
            {"name_en": "Chicken Sandwich",               "name_ar": "ساندويش دجاج",               "category": "Sandwich","calories": 470, "protein_g": 28, "carbs_g": 44, "fat_g": 20, "sodium_mg": 860,  "fiber_g": 2},
            {"name_en": "Spicy Chicken Wings 6 pieces",   "name_ar": "أجنحة دجاج حارة 6 قطع",     "category": "Main",    "calories": 480, "protein_g": 34, "carbs_g": 18, "fat_g": 30, "sodium_mg": 960,  "fiber_g": 1},
            {"name_en": "French Fries Medium",            "name_ar": "بطاطس مقلية وسط",            "category": "Side",    "calories": 320, "protein_g": 4,  "carbs_g": 42, "fat_g": 15, "sodium_mg": 430,  "fiber_g": 3},
        ],
    },

    "maestro": {
        "name_en": "Maestro Pizza",
        "name_ar": "مايسترو بيتزا",
        "category": "Pizza",
        "emoji": "🍕",
        "color": "#c0392b",
        "items": [
            {"name_en": "Chicken Tikka Pizza 1 Slice",    "name_ar": "بيتزا دجاج تيكا شريحة",     "category": "Pizza",   "calories": 270, "protein_g": 14, "carbs_g": 28, "fat_g": 12, "sodium_mg": 560,  "fiber_g": 1},
            {"name_en": "BBQ Meat Pizza 1 Slice",         "name_ar": "بيتزا لحم بي بي كيو شريحة", "category": "Pizza",   "calories": 310, "protein_g": 15, "carbs_g": 30, "fat_g": 15, "sodium_mg": 680,  "fiber_g": 1},
            {"name_en": "Mixed Seafood Pizza 1 Slice",    "name_ar": "بيتزا مأكولات بحرية شريحة", "category": "Pizza",   "calories": 260, "protein_g": 14, "carbs_g": 28, "fat_g": 11, "sodium_mg": 520,  "fiber_g": 1},
            {"name_en": "Cheese Pizza 1 Slice",           "name_ar": "بيتزا جبن شريحة",           "category": "Pizza",   "calories": 240, "protein_g": 10, "carbs_g": 28, "fat_g": 10, "sodium_mg": 460,  "fiber_g": 1},
            {"name_en": "Pasta Chicken Alfredo",          "name_ar": "باستا دجاج ألفريدو",        "category": "Pasta",   "calories": 550, "protein_g": 28, "carbs_g": 56, "fat_g": 24, "sodium_mg": 880,  "fiber_g": 3},
            {"name_en": "Garlic Bread with Cheese",       "name_ar": "خبز ثوم بالجبن",            "category": "Side",    "calories": 260, "protein_g": 8,  "carbs_g": 28, "fat_g": 13, "sodium_mg": 420,  "fiber_g": 1},
        ],
    },
}